import React from 'react';
import EmotionBadge from './EmotionBadge';
import './StoryCard.css';

const StoryCard = ({ story, onClick }) => {
  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const getPatternTypeIcon = () => {
    if (!story.story_metadata) return '📖';

    const patternType = story.story_metadata.pattern_type;
    switch (patternType) {
      case 'temporal':
        return '📅';
      case 'spatial':
        return '📍';
      case 'visual':
        return '🎨';
      default:
        return '📖';
    }
  };

  const truncateDescription = (text, maxLength = 120) => {
    if (!text) return '';
    if (text.length <= maxLength) return text;
    return text.substring(0, maxLength) + '...';
  };

  const getNarrativeToneBadge = () => {
    if (!story.narrative_tone) return null;
    const toneEmojis = {
      joyful: '😊',
      nostalgic: '🌅',
      celebratory: '🎉',
      reflective: '💭'
    };
    return (
      <span className="narrative-tone-badge" title={`Tone: ${story.narrative_tone}`}>
        {toneEmojis[story.narrative_tone] || '📖'} {story.narrative_tone}
      </span>
    );
  };

  // Get dominant emotion
  const getDominantEmotion = () => {
    if (!story.emotions || story.emotions.length === 0) return null;
    // emotions is an array, find the one with highest percentage
    const sorted = [...story.emotions].sort((a, b) => b.percentage - a.percentage);
    return sorted[0];
  };

  return (
    <div className="story-card" onClick={onClick}>
      <div className="story-card-header">
        <span className="story-icon">{getPatternTypeIcon()}</span>
        <h3 className="story-title">{story.title}</h3>
      </div>

      <p className="story-description">
        {truncateDescription(story.description)}
      </p>

      {/* Emotion Badge */}
      {getDominantEmotion() && (
        <div className="story-emotion">
          <EmotionBadge
            emotion={getDominantEmotion().emotion || getDominantEmotion().name}
            percentage={getDominantEmotion().percentage}
            size="small"
          />
        </div>
      )}

      <div className="story-card-footer">
        <div className="story-meta">
          <span className="image-count">
            📷 {story.image_count || 0} {story.image_count === 1 ? 'photo' : 'photos'}
          </span>
          <span className="story-date">
            {formatDate(story.created_at)}
          </span>
        </div>

        <div className="story-badges">
          {story.story_metadata?.source === 'pattern_based' && (
            <span className="auto-generated-badge">Auto-generated</span>
          )}
          {story.story_metadata?.generation_method === 'llm_generated' && (
            <span className="ai-generated-badge" title="Generated by AI">🤖 AI</span>
          )}
          {getNarrativeToneBadge()}
        </div>
      </div>
    </div>
  );
};

export default StoryCard;
